import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";

export const metadata: Metadata = {
  title: "Trevola",
  description: "Generated by create next app",
};

const muslish = Mulish({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={muslish.className}>
        <ConvexClientProvider>
         {children}
        </ConvexClientProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
